## Mengimport data menggunakan pandas

In [96]:
import pandas as pd
import numpy as np

In [97]:
data_train = pd.read_csv('.\DatasetEskperimen\CensusIncome\CencusIncome.data.txt')
data_test = pd.read_csv('.\DatasetEskperimen\CensusIncome\CencusIncome.test.txt')

In [98]:
data = pd.concat([data_train, data_test], keys=['train', 'test'])

## Mengubah kolom class menjadi numerik

In [99]:
def changeClassToNumber(x):
    if x == '<=50K':
        return 0
    elif x == '>50K':
        return 1
    else:
        return -1

In [100]:
data['class'] = data['class'].map(lambda x: changeClassToNumber(x))

## Menghandle missing value

In [101]:
print("Banyaknya data:", len(data))
print("--------------------------------------------------------------------")
print(data.info())

Banyaknya data: 48842
--------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48842 entries, (train, 0) to (test, 16280)
Data columns (total 15 columns):
age               48842 non-null int64
workclass         46043 non-null object
fnlwgt            48842 non-null int64
education         48842 non-null object
education-num     48842 non-null int64
marital-status    48842 non-null object
occupation        46033 non-null object
relationship      48842 non-null object
race              48842 non-null object
sex               48842 non-null object
capital-gain      48842 non-null int64
capital-loss      48842 non-null int64
hours-per-week    48842 non-null int64
native-country    47985 non-null object
class             48842 non-null int64
dtypes: int64(7), object(8)
memory usage: 6.0+ MB
None

Karena object yang memiliki missing value adalah object, maka missing value akan digantikan dengan nilai modus dari kolom tersebut

In [102]:
data["workclass"].fillna(data["workclass"].mode()[0], inplace=True)
data["occupation"].fillna(data["occupation"].mode()[0], inplace=True)
data["native-country"].fillna(data["native-country"].mode()[0], inplace=True)

In [103]:

data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48842 entries, (train, 0) to (test, 16280)
Data columns (total 15 columns):
age               48842 non-null int64
workclass         48842 non-null object
fnlwgt            48842 non-null int64
education         48842 non-null object
education-num     48842 non-null int64
marital-status    48842 non-null object
occupation        48842 non-null object
relationship      48842 non-null object
race              48842 non-null object
sex               48842 non-null object
capital-gain      48842 non-null int64
capital-loss      48842 non-null int64
hours-per-week    48842 non-null int64
native-country    48842 non-null object
class             48842 non-null int64
dtypes: int64(7), object(8)
memory usage: 6.0+ MB

In [104]:
def one_hot_encode(df, label):
    onehot = pd.get_dummies(df[label],prefix=label)
    df.drop(label, axis=1,inplace = True)
    return df.join(onehot)

In [105]:
def changeSexToNumber(x):
    if x == 'Female':
        return 0
    elif x == 'Male':
        return 1
    else:
        return np.nan

#data.drop('race',axis=1, inplace=True)
#data.drop('native-country',axis=1, inplace=True)

In [106]:
data = one_hot_encode(data.drop("class", axis=1), "workclass").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "education").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "marital-status").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "occupation").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "relationship").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "race").join(data["class"])
data = one_hot_encode(data.drop("class", axis=1), "native-country").join(data["class"])
data['sex'] = data['sex'].map(lambda x: changeSexToNumber(x))

In [107]:
data.drop('fnlwgt',axis=1, inplace=True)
#data.drop('hours-per-week',axis=1, inplace=True)

In [108]:
data

             age  education-num  sex  capital-gain  capital-loss  \
train 0       39             13    1          2174             0
      1       50             13    1             0             0
      2       38              9    1             0             0
      3       53              7    1             0             0
      4       28             13    0             0             0
      5       37             14    0             0             0
      6       49              5    0             0             0
      7       52              9    1             0             0
      8       31             14    0         14084             0
      9       42             13    1          5178             0
      10      37             10    1             0             0
      11      30             13    1             0             0
      12      23             13    0             0             0
      13      32             12    1             0             0
      14      40             11    1             0             0
      15      34              4    1             0             0
      16      25              9    1             0             0
      17      32              9    1             0             0
      18      38              7    1             0             0
      19      43             14    0             0             0
      20      40             16    1             0             0
      21      54              9    0             0             0
      22      35              5    1             0             0
      23      43              7    1             0          2042
      24      59              9    0             0             0
      25      56             13    1             0             0
      26      19              9    1             0             0
      27      54             10    1             0             0
      28      39              9    1             0             0
      29      49              9    1             0             0
...          ...            ...  ...           ...           ...
test  16251   81             11    1          2936             0
      16252   60             11    1          7688             0
      16253   39             13    0             0          1669
      16254   38             14    1             0             0
      16255   43             14    1             0          1902
      16256   23              9    1             0             0
      16257   73             10    0             0             0
      16258   35             10    1             0             0
      16259   66              9    0             0             0
      16260   27             10    0             0             0
      16261   40             15    1         15024             0
      16262   51              9    1             0             0
      16263   22             10    1             0             0
      16264   64              9    1             0             0
      16265   50             14    0             0             0
      16266   55              9    0             0             0
      16267   38             11    0             0             0
      16268   58             12    1             0             0
      16269   32              9    1             0             0
      16270   48              9    1             0             0
      16271   61              9    1             0             0
      16272   31              9    1             0             0
      16273   25              9    0             0             0
      16274   48             14    1             0             0
      16275   33             13    1             0             0
      16276   39             13    0             0             0
      16277   64              9    1             0             0
      16278   38             13    1             0             0
      16279   44             13    1          5455             0
      16280   35             13    1             0             0

             hours-per-week  workclass_Federal-gov  workclass_Local-gov  \
train 0                  40                      0                    0
      1                  13                      0                    0
      2                  40                      0                    0
      3                  40                      0                    0
      4                  40                      0                    0
      5                  40                      0                    0
      6                  16                      0                    0
      7                  45                      0                    0
      8                  50                      0                    0
      9                  40                      0                    0
      10                 80                      0                    0
      11                 40                      0                    0
      12                 30                      0                    0
      13                 50                      0                    0
      14                 40                      0                    0
      15                 45                      0                    0
      16                 35                      0                    0
      17                 40                      0                    0
      18                 50                      0                    0
      19                 45                      0                    0
      20                 60                      0                    0
      21                 20                      0                    0
      22                 40                      1                    0
      23                 40                      0                    0
      24                 40                      0                    0
      25                 40                      0                    1
      26                 40                      0                    0
      27                 60                      0                    0
      28                 80                      0                    0
      29                 40                      0                    0
...                     ...                    ...                  ...
test  16251              20                      0                    0
      16252              40                      0                    0
      16253              40                      0                    0
      16254              50                      0                    0
      16255              50                      0                    1
      16256              40                      0                    0
      16257              40                      0                    0
      16258              40                      0                    0
      16259               8                      0                    0
      16260              45                      0                    0
      16261              55                      0                    0
      16262              40                      0                    0
      16263              40                      0                    0
      16264              32                      0                    0
      16265              40                      0                    1
      16266              32                      0                    0
      16267              40                      0                    0
      16268              36                      0                    0
      16269              40                      0                    0
      16270              40                      0                    0
      16271              48                      0                    0
      16272              40                      0                    0
      16273              40                      0                    0
      16274              40                      0                    1
      16275              40                      0                    0
      16276              36                      0                    0
      16277              40                      0                    0
      16278              50                      0                    0
      16279              40                      0                    0
      16280              60                      0                    0

             workclass_Never-worked  workclass_Private  ...    \
train 0                           0                  0  ...
      1                           0                  0  ...
      2                           0                  1  ...
      3                           0                  1  ...
      4                           0                  1  ...
      5                           0                  1  ...
      6                           0                  1  ...
      7                           0                  0  ...
      8                           0                  1  ...
      9                           0                  1  ...
      10                          0                  1  ...
      11                          0                  0  ...
      12                          0                  1  ...
      13                          0                  1  ...
      14                          0                  1  ...
      15                          0                  1  ...
      16                          0                  0  ...
      17                          0                  1  ...
      18                          0                  1  ...
      19                          0                  0  ...
      20                          0                  1  ...
      21                          0                  1  ...
      22                          0                  0  ...
      23                          0                  1  ...
      24                          0                  1  ...
      25                          0                  0  ...
      26                          0                  1  ...
      27                          0                  1  ...
      28                          0                  1  ...
      29                          0                  1  ...
...                             ...                ...  ...
test  16251                       0                  1  ...
      16252                       0                  1  ...
      16253                       0                  1  ...
      16254                       0                  1  ...
      16255                       0                  0  ...
      16256                       0                  1  ...
      16257                       0                  0  ...
      16258                       0                  1  ...
      16259                       0                  1  ...
      16260                       0                  1  ...
      16261                       0                  1  ...
      16262                       0                  1  ...
      16263                       0                  1  ...
      16264                       0                  0  ...
      16265                       0                  0  ...
      16266                       0                  1  ...
      16267                       0                  1  ...
      16268                       0                  1  ...
      16269                       0                  1  ...
      16270                       0                  1  ...
      16271                       0                  1  ...
      16272                       0                  1  ...
      16273                       0                  1  ...
      16274                       0                  0  ...
      16275                       0                  1  ...
      16276                       0                  1  ...
      16277                       0                  1  ...
      16278                       0                  1  ...
      16279                       0                  1  ...
      16280                       0                  0  ...

             native-country_Puerto-Rico  native-country_Scotland  \
train 0                               0                        0
      1                               0                        0
      2                               0                        0
      3                               0                        0
      4                               0                        0
      5                               0                        0
      6                               0                        0
      7                               0                        0
      8                               0                        0
      9                               0                        0
      10                              0                        0
      11                              0                        0
      12                              0                        0
      13                              0                        0
      14                              0                        0
      15                              0                        0
      16                              0                        0
      17                              0                        0
      18                              0                        0
      19                              0                        0
      20                              0                        0
      21                              0                        0
      22                              0                        0
      23                              0                        0
      24                              0                        0
      25                              0                        0
      26                              0                        0
      27                              0                        0
      28                              0                        0
      29                              0                        0
...                                 ...                      ...
test  16251                           0                        0
      16252                           0                        0
      16253                           0                        0
      16254                           0                        0
      16255                           0                        0
      16256                           0                        0
      16257                           0                        0
      16258                           0                        0
      16259                           0                        0
      16260                           0                        0
      16261                           0                        0
      16262                           0                        0
      16263                           0                        0
      16264                           0                        0
      16265                           0                        0
      16266                           0                        0
      16267                           0                        0
      16268                           0                        0
      16269                           0                        0
      16270                           0                        0
      16271                           0                        0
      16272                           0                        0
      16273                           0                        0
      16274                           0                        0
      16275                           0                        0
      16276                           0                        0
      16277                           0                        0
      16278                           0                        0
      16279                           0                        0
      16280                           0                        0

             native-country_South  native-country_Taiwan  \
train 0                         0                      0
      1                         0                      0
      2                         0                      0
      3                         0                      0
      4                         0                      0
      5                         0                      0
      6                         0                      0
      7                         0                      0
      8                         0                      0
      9                         0                      0
      10                        0                      0
      11                        0                      0
      12                        0                      0
      13                        0                      0
      14                        0                      0
      15                        0                      0
      16                        0                      0
      17                        0                      0
      18                        0                      0
      19                        0                      0
      20                        0                      0
      21                        0                      0
      22                        0                      0
      23                        0                      0
      24                        0                      0
      25                        0                      0
      26                        0                      0
      27                        1                      0
      28                        0                      0
      29                        0                      0
...                           ...                    ...
test  16251                     0                      0
      16252                     0                      0
      16253                     0                      0
      16254                     0                      0
      16255                     0                      0
      16256                     0                      0
      16257                     0                      0
      16258                     0                      0
      16259                     0                      0
      16260                     0                      0
      16261                     0                      0
      16262                     0                      0
      16263                     0                      0
      16264                     0                      0
      16265                     0                      0
      16266                     0                      0
      16267                     0                      0
      16268                     0                      0
      16269                     0                      0
      16270                     0                      0
      16271                     0                      0
      16272                     0                      0
      16273                     0                      0
      16274                     0                      0
      16275                     0                      0
      16276                     0                      0
      16277                     0                      0
      16278                     0                      0
      16279                     0                      0
      16280                     0                      0

             native-country_Thailand  native-country_Trinadad&Tobago  \
train 0                            0                               0

In [109]:
from sklearn.preprocessing import Normalizer
feature = data.drop("class",axis=1).columns

In [110]:
feature

Index(['age', 'education-num', 'sex', 'capital-gain', 'capital-loss',
       'hours-per-week', 'workclass_Federal-gov', 'workclass_Local-gov',
       'workclass_Never-worked', 'workclass_Private',
       ...
       'native-country_Portugal', 'native-country_Puerto-Rico',
       'native-country_Scotland', 'native-country_South',
       'native-country_Taiwan', 'native-country_Thailand',
       'native-country_Trinadad&Tobago', 'native-country_United-States',
       'native-country_Vietnam', 'native-country_Yugoslavia'],
      dtype='object', length=103)

In [111]:
scaler = MinMaxScaler()

In [112]:
data[feature] = scaler.fit_transform(data.drop("class", axis=1))

In [113]:
from sklearn.neural_network import 
from sklearn.metrics import accuracy_score

In [114]:
dt = MLPClassifier(hidden_layer_sizes=(52,52))

In [115]:
dt.fit(data.loc['train'].drop('class',axis=1).values, data.loc['train']['class'])

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(52, 52), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [116]:
y_hat = dt.predict(data.loc['test'].drop('class',axis=1))

In [117]:
accuracy_score(data.loc["test"]['class'].values, y_hat)

0.84165591794115846

In [ ]:
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
%matplotlib inline

In [ ]:
X = data.drop("class", axis=1).values

In [ ]:
X = scale(X)
pca = PCA()
pca.fit(X)
var = pca.explained_variance_ratio_
var1 = np.cumsum(np.round(pca.explained_variance_ratio_, decimals=4)*100)

In [ ]:
plt.figure(figsize=(10,10))
plt.xlabel('Principal Component')
plt.ylabel('Cumulative Proportion of Variance Explained')
plt.plot(var1,"o--")
plt.savefig('PCA.png')

In [ ]:
var1[95]

Dari gambar bisa diambil hanya 85 Point Component yang akan diambil

In [ ]:
X = data.drop("class", axis=1).values
n = 95

In [ ]:
X = scale(X)
pca = PCA(n_components=n)
pca.fit(X)

In [ ]:
X = pca.transform(X)

In [ ]:
X.shape

In [ ]:
data_dummy = pd.DataFrame(X)

In [ ]:
data["class"]

In [ ]:
data_train = data_dummy[:32561].join(data.loc['train']['class'])
data_test = data_dummy[32561:].reset_index().join(data.loc['test']['class'])
data_test.drop('index',axis=1, inplace=True)

In [ ]:
len(data_test)

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
nb = MLPClassifier(hidden_layer_sizes=(48,48),activation='logistic')

In [ ]:
nb.fit(data_train.drop("class", axis=1).values, data_train["class"].values)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_hat = nb.predict(data_test.drop("class",axis=1).values)

In [ ]:
accuracy_score(data.loc["test"]['class'].values, y_hat)